# Generated by Django 6.0.4 on 2026-09-21 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Remedio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dosagem', models.CharField(max_length=50)),
                ('quantidade', models.IntegerField(default=0)),
                ('horario', models.TimeField(blank=True, null=True)),
                ('observacoes', models.CharField(blank=True, max_length=500, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remedios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
